### ISSUE TITLE
Replies

### ISSUE THREAD

**Issue by patabrava** [LycurgusxLycurgus/twitter_starfish#3]
Add replies

**Comment by LycurgusxLycurgus** [comment]
you need to get into twitter and provide the scraping instructions with code from devtools

**Comment by LycurgusxLycurgus** [comment]
ask ai 
![image](https://github.com/user-attachments/assets/1d9dc913-64e4-41ad-b23e-299f18beacee)
what you need to copy so it can scrape and create actions properly
